version: '3.7'

services:
    postgres: 
        image: postgres
        container_name: postgres-admin-apa
        environment: 
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: apaWS_DB
        ports: 
            - "5432:5432"
        volumes:
            - ../../scripts/postgres/:/docker-entrypoint-initdb.b
        networks:
            - admin-apa
networks: 
    admin-apa:
        driver: bridge